### ISSUE TITLE
cocoapods install wrong library

### ISSUE THREAD

**Issue by ttuygun** [hico17/EzRealm#3]
it install https://github.com/markcdb/RealmManager

**Comment by hico17** [comment]
Hello ttuygun,
as mentioned in the readme I will integrate Cocoapods later (probably I will do it in these days, and I will change the pod name too 😪).
If you prefer to use it now, you can import the library manually in your workspace!

**Comment by hico17** [comment]
Hello ttuygun,
the pod is now available as EzRealm
:)
